apiVersion: v1
kind: Pod
metadata:
  name: vault-audit-stackdriver
spec:
  containers:
  - name: vault-server
    image: vault
    args:
    - /bin/sh
    - -c
    - >
      mkfifo -m 600 /tmp/logpipe;
      cat <> /tmp/logpipe 1>&2 &
      exec vault server -dev
    env:
    - name: VAULT_DEV_ROOT_TOKEN_ID
      value: token
  - name: vault-client
    image: vault
    args:
    - /bin/sh
    - -c
    - >
      sleep 5;
      vault audit-enable file path=/tmp/logpipe mode=666;
      while true;
      do
        vault list secret/stuff;
        sleep 3;
      done
    env:
    - name: VAULT_TOKEN
      value: token
    - name: VAULT_ADDR
      value: http://localhost:8200
